set number
set linebreak
set showbreak=+++
set showmatch
set visualbell

set hlsearch
set smartcase
set ignorecase
set incsearch

set autoindent
set cindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4

set ruler

set cursorline
set cursorcolumn

set undolevels=1000
set backspace=indent,eol,start
hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white

packloadall
silent! helptags ALL

" See https://draculatheme.com/vim
packadd! dracula
syntax enable
colorscheme dracula

hi ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
